version: '2'
services:
  caddy:
    image: kanej/caddy:v0.9.5
    ports:
      - "80:2015"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: DevelopmentDockerfile
    volumes:
      - .:/antaeus
    depends_on:
      - ipfs
      - etcd
    environment:
      - NODE_ENV=production
  ipfs:
    image: ipfs/go-ipfs:v0.4.7
    ports:
      - "4001:4001"
  etcd:
    image: quay.io/coreos/etcd:v3.1.3
    command: >
      etcd
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
